@startuml
 
start
partition #00000010 Initialization {
    :Update Job Execution History table;
    note left
        Mark experiments that have
        not finished as cancelled.
    end note
    :Update Job table;
    note left
        Mark processing jobs as processed.
    end note
}
repeat
    if (Jobs with status "SUBMITTED" in job table?) then (yes)
        while (Jobs to process?) is (yes)
            partition #00000010 Job Processing {
                :Update Job Status
                to "PROCESSING";
                :Write job to Job
                Iteration table;
                :Create "PreProcessingTask";
                :Put PreProcessingTask in
                pre-processing queue;
            }
        endwhile (no)
    else (no)
        :Wait for a
        predefined interval;
    endif
repeat while (Should exit) is (no)

:Shutdown Scheduler;

stop
@enduml
