@startuml
 
start
partition #00000010 Initialization {
    :Update job_runs table;
    note left
        Mark experiments that are
        not finished as CANCELLED.
    end note
    :Update job_submissions table;
    note left
        Mark PROCESSING jobs as PROCESSED.
    end note
}
repeat
    if (Jobs with status "SUBMITTED" in job table?) then (yes)
        while (Jobs to process?) is (yes)
            partition #00000010 Job Processing {
                :Update Job Status
                to "PROCESSING";
                :Create job run and
                insert into job_runs table;
                :Create "PreProcessingTask";
                :Put PreProcessingTask in
                pre-processing queue;
            }
        endwhile (no)
    else (no)
        :Wait for a
        predefined interval;
    endif
repeat while (Should exit) is (no)

:Shutdown Scheduler;

stop
@enduml
