import { ScanParameterGenerationSpec } from "../types/ScanParameterGenerationSpec";
import { ScanPattern } from "../types/ScanParameterInfo";

/**
 * Generates the scan values a parameter is stepped through, in scan order.
 *
 * @param start - First value of the range.
 * @param stop - Last value of the range.
 * @param points - Number of points the range is divided into.
 * @param pattern - Order in which the range is walked.
 * @returns The scan values in the order they are scanned.
 */
export const generateScanValues = (
  start: number,
  stop: number,
  points: number,
  pattern: ScanPattern,
) => {
  const linspace = (n: number) =>
    Array.from({ length: n }, (_, i) => start + (i * (stop - start)) / (n - 1));

  switch (pattern) {
    case "linear":
      return linspace(points);
    case "scatter":
      return linspace(points).sort(() => Math.random() - 0.5);
    case "centred": {
      const base = linspace(points);
      const mid = Math.floor((points - 1) / 2);
      const order = [mid];
      for (let k = 1; order.length < points; k++) {
        if (mid - k >= 0) order.push(mid - k);
        if (mid + k < points) order.push(mid + k);
      }
      return order.map((i) => base[i]);
    }
    case "forwardReverse": {
      const base = linspace(points);
      return [...base, ...base.reverse()];
    }
  }
};

/**
 * Number of scan values `generateScanValues` produces for a generation spec.
 *
 * The forward-and-reverse pattern walks the range twice, so it yields twice as many
 * values as `points`; every other pattern yields exactly `points` values.
 *
 * @param generation - The generation spec of a scan parameter.
 * @returns The number of values the parameter is scanned over.
 */
export const scanValueCount = (generation: ScanParameterGenerationSpec): number =>
  generation.pattern === "forwardReverse" ? generation.points * 2 : generation.points;

/**
 * Constructs a unique key for identifying a scanned parameter.
 *
 * For experiment parameters, this returns the parameter ID as-is.
 * For device parameters (i.e., when namespace is "Devices"), it returns
 * the full access path used to uniquely identify the parameter, including
 * the device name.
 *
 * Example:
 *   makeScannedParamKey("laser_power", "Devices", "Laser A")
 *   → 'devices.device_proxies["Laser A"].laser_power'
 *
 * @param id - The parameter ID.
 * @param namespace - The parameter's namespace (e.g., "Devices" or an experiment namespace).
 * @param deviceNameOrDisplayGroup - Device name (for device parameters) or display group name.
 * @returns A string key uniquely identifying the scanned parameter.
 */
export const makeScannedParamKey = (
  id: string,
  namespace: string,
  deviceNameOrDisplayGroup: string,
): string =>
  namespace === "Devices"
    ? `devices.device_proxies["${deviceNameOrDisplayGroup}"].${id}`
    : id;

/**
 * Inverse of makeScannedParamKey: recovers the bare parameter id from a scanned
 * key. For device parameters it strips the `devices.device_proxies["<device>"].`
 * prefix; for other namespaces the key is already the bare id.
 *
 * @param scannedKey - The full scanned parameter key (as built by makeScannedParamKey).
 * @param namespace - The parameter's namespace (e.g., "Devices").
 * @param deviceNameOrDisplayGroup - Device name (for device parameters) or display group name.
 * @returns The bare parameter id.
 */
export const extractScannedParamId = (
  scannedKey: string,
  namespace: string,
  deviceNameOrDisplayGroup: string,
): string => {
  if (namespace !== "Devices") return scannedKey;
  const prefix = `devices.device_proxies["${deviceNameOrDisplayGroup}"].`;
  return scannedKey.startsWith(prefix) ? scannedKey.slice(prefix.length) : scannedKey;
};

/**
 * Returns the index of a scanned parameter within the scanned parameters list.
 *
 * This function checks if the given `paramId` exists in the `scannedParams` array
 * and returns its index if found. If the parameter is not found, it returns null.
 *
 * @param paramId - The full key identifying the parameter (as generated by makeScannedParamKey).
 * @param scannedParams - The list of scanned parameter keys.
 * @returns The index of the parameter in the scan list, or null if not found.
 */
export const getScanIndex = (
  paramId: string,
  scannedParams: string[],
): number | null => {
  const index = scannedParams.indexOf(paramId);
  return index !== -1 ? index : null;
};

/**
 * Determines if a parameter type can be scanned with numeric ranges.
 *
 * @param paramId - The parameter ID string containing type information.
 * @returns True if the parameter can be scanned (numeric types), false otherwise.
 */
export function isScannableParameterType(paramId: string): boolean {
  if (paramId.includes("param_type='ParameterTypes.BOOLEAN'")) {
    return false;
  }

  if (paramId.includes("param_type='ParameterTypes.ENUM'")) {
    return false;
  }

  return true;
}
