"""Changes ExperimentSource table

Revision ID: 089abe6a0eed
Revises: 4c4713742c14
Create Date: 2024-12-17 11:40:01.075455

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "089abe6a0eed"
down_revision: str | None = "4c4713742c14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("experiment_sources", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("experiment_id", sa.String(), server_default="", nullable=False)
        )
        batch_op.drop_constraint("source_location", type_="unique")
        batch_op.drop_column("file_path")
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade() -> None:
    # No downgrade is supplied
    pass
