"""Adds device_id to scan_parameters table

Revision ID: 1dbf22d794c7
Revises: 5f18f70e500a
Create Date: 2025-06-23 15:12:15.207678

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1dbf22d794c7"
down_revision: str | None = "5f18f70e500a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_parameters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("device_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_devices", "devices", ["device_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_parameters", schema=None) as batch_op:
        batch_op.drop_constraint("fk_devices", type_="foreignkey")
        batch_op.drop_column("device_id")

    # ### end Alembic commands ###
