"""Adds retry_attempts and retry_delay_seconds to devices table

Revision ID: 2bc7556020cf
Revises: 5f18f70e500a
Create Date: 2025-06-26 09:40:08.807366

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bc7556020cf"
down_revision: str | None = "5f18f70e500a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "retry_attempts", sa.Integer(), nullable=False, server_default="3"
            )
        )
        batch_op.add_column(
            sa.Column(
                "retry_delay_seconds", sa.Float(), nullable=False, server_default="0.0"
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_column("retry_delay_seconds")
        batch_op.drop_column("retry_attempts")

    # ### end Alembic commands ###
