"""Adds scan_parameters table

Revision ID: 5b41d0d6c856
Revises: 089abe6a0eed
Create Date: 2024-12-17 14:09:52.531594

"""

from collections.abc import Sequence

import sqlalchemy as sa

import icon.server.data_access.models.sqlite.scan_parameter
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b41d0d6c856"
down_revision: str | None = "089abe6a0eed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_parameters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("variable_id", sa.String(), nullable=False),
        sa.Column(
            "scan_values",
            icon.server.data_access.models.sqlite.scan_parameter.JSONEncodedList(),
            nullable=False,
        ),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scan_parameters")
    # ### end Alembic commands ###
