"""Removes priority column from job iteration table

Revision ID: 8640dcfde6f0
Revises: f5fd45fdded6
Create Date: 2024-08-08 16:48:41.843170

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8640dcfde6f0"
down_revision: str | None = "f5fd45fdded6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_iterations", schema=None) as batch_op:
        batch_op.drop_index("by_job_id_and_status")
        batch_op.create_index(
            "by_job_id_and_status", ["job_id", "status", "scheduled_time"], unique=False
        )
        batch_op.drop_column("priority")
        batch_op.drop_constraint("priority_ge_0")
        batch_op.drop_constraint("priority_le_20")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_iterations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("priority", sa.INTEGER(), server_default="20", nullable=False)
        )
        batch_op.drop_index("by_job_id_and_status")
        batch_op.create_index(
            "by_job_id_and_status",
            ["job_id", "status", "priority", "scheduled_time"],
            unique=False,
        )
        batch_op.create_check_constraint("priority_ge_0", "priority >= 0")
        batch_op.create_check_constraint("priority_le_20", "priority <= 20")

    # ### end Alembic commands ###
