/**
 * Constructs a unique key for identifying a scanned parameter.
 *
 * For experiment parameters, this returns the parameter ID as-is.
 * For device parameters (i.e., when namespace is "Devices"), it returns
 * the full access path used to uniquely identify the parameter, including
 * the device name.
 *
 * Example:
 *   makeScannedParamKey("laser_power", "Devices", "Laser A")
 *   → 'devices.device_proxies["Laser A"].laser_power'
 *
 * @param id - The parameter ID.
 * @param namespace - The parameter's namespace (e.g., "Devices" or an experiment namespace).
 * @param deviceNameOrDisplayGroup - Device name (for device parameters) or display group name.
 * @returns A string key uniquely identifying the scanned parameter.
 */
export const makeScannedParamKey = (
  id: string,
  namespace: string,
  deviceNameOrDisplayGroup: string,
): string =>
  namespace === "Devices"
    ? `devices.device_proxies["${deviceNameOrDisplayGroup}"].${id}`
    : id;

/**
 * Inverse of makeScannedParamKey: recovers the bare parameter id from a scanned
 * key. For device parameters it strips the `devices.device_proxies["<device>"].`
 * prefix; for other namespaces the key is already the bare id.
 *
 * @param scannedKey - The full scanned parameter key (as built by makeScannedParamKey).
 * @param namespace - The parameter's namespace (e.g., "Devices").
 * @param deviceNameOrDisplayGroup - Device name (for device parameters) or display group name.
 * @returns The bare parameter id.
 */
export const extractScannedParamId = (
  scannedKey: string,
  namespace: string,
  deviceNameOrDisplayGroup: string,
): string => {
  if (namespace !== "Devices") return scannedKey;
  const prefix = `devices.device_proxies["${deviceNameOrDisplayGroup}"].`;
  return scannedKey.startsWith(prefix) ? scannedKey.slice(prefix.length) : scannedKey;
};

/**
 * Returns the index of a scanned parameter within the scanned parameters list.
 *
 * This function checks if the given `paramId` exists in the `scannedParams` array
 * and returns its index if found. If the parameter is not found, it returns null.
 *
 * @param paramId - The full key identifying the parameter (as generated by makeScannedParamKey).
 * @param scannedParams - The list of scanned parameter keys.
 * @returns The index of the parameter in the scan list, or null if not found.
 */
export const getScanIndex = (
  paramId: string,
  scannedParams: string[],
): number | null => {
  const index = scannedParams.indexOf(paramId);
  return index !== -1 ? index : null;
};

/**
 * Determines if a parameter type can be scanned with numeric ranges.
 *
 * @param paramId - The parameter ID string containing type information.
 * @returns True if the parameter can be scanned (numeric types), false otherwise.
 */
export function isScannableParameterType(paramId: string): boolean {
  if (paramId.includes("param_type='ParameterTypes.BOOLEAN'")) {
    return false;
  }

  if (paramId.includes("param_type='ParameterTypes.ENUM'")) {
    return false;
  }

  return true;
}
