/**
 * Returns the index of a scanned parameter within the scanned parameters list.
 *
 * This function checks if the given `paramId` exists in the `scannedParams` array
 * and returns its index if found. If the parameter is not found, it returns null.
 *
 * @param paramId - The full key identifying the parameter (as generated by makeScannedParamKey).
 * @param scannedParams - The list of scanned parameter keys.
 * @returns The index of the parameter in the scan list, or null if not found.
 */
export const getScanIndex = (
  paramId: string,
  scannedParams: string[],
): number | null => {
  const index = scannedParams.indexOf(paramId);
  return index !== -1 ? index : null;
};

/**
 * Determines if a parameter type can be scanned with numeric ranges.
 *
 * @param paramId - The parameter ID string containing type information.
 * @returns True if the parameter can be scanned (numeric types), false otherwise.
 */
export function isScannableParameterType(paramId: string): boolean {
  if (paramId.includes("param_type='ParameterTypes.BOOLEAN'")) {
    return false;
  }

  if (paramId.includes("param_type='ParameterTypes.ENUM'")) {
    return false;
  }

  return true;
}
