import { GroupsByNamespace } from "../hooks/useParameterDisplayGroups";
import { Store } from "../stores/parmeterStore";
import { ScanParameterInfo } from "../types/ScanParameterInfo";

export interface ScanParameterBounds {
  min: number | null;
  max: number | null;
}

/**
 * Refreshes Span-mode parameters' start/stop from each parameter's current live
 * value, keeping the remembered span. Span mode never stores a "center" — it's
 * always the parameter's live value, looked up here fresh (typically right before
 * submitting a job) rather than reused from whenever the span was last edited.
 *
 * Parameters not in Span mode, or whose live value isn't known/numeric, are
 * returned unchanged.
 *
 * @param parameters - The scan parameters to refresh.
 * @param parameterStore - Store to read live parameter values from.
 * @returns A new parameters array with Span-mode entries re-centred.
 */
export const refreshSpanCenterParameters = (
  parameters: ScanParameterInfo[],
  parameterStore: Pick<Store, "get"> | null,
): ScanParameterInfo[] =>
  parameters.map((param) => {
    if ((param.generation.inputMode ?? "startStop") !== "spanCenter") return param;
    const liveValue = parameterStore?.get(param.id);
    if (typeof liveValue !== "number") return param;
    const span = Math.abs(param.generation.stop - param.generation.start);
    return {
      ...param,
      generation: {
        ...param.generation,
        start: liveValue - span / 2,
        stop: liveValue + span / 2,
      },
    };
  });

/**
 * Looks up the allowed value range of a scan parameter from the display group
 * metadata (as provided by the experiment library).
 *
 * Device and realtime parameters carry no range metadata, so their bounds are null.
 *
 * @param param - The scan parameter to look up.
 * @param parameterDisplayGroups - Display group metadata keyed by "namespace (group)".
 * @returns The parameter's min/max bounds, null when unbounded or unknown.
 */
export const getScanParameterBounds = (
  param: ScanParameterInfo,
  parameterDisplayGroups: GroupsByNamespace,
): ScanParameterBounds => {
  if (
    !param.namespace ||
    !param.deviceNameOrDisplayGroup ||
    param.namespace === "Devices" ||
    param.namespace === "Real Time"
  ) {
    return { min: null, max: null };
  }
  const group =
    parameterDisplayGroups[`${param.namespace} (${param.deviceNameOrDisplayGroup})`];
  const metadata = group?.[param.id];
  return {
    min: metadata?.min_value ?? null,
    max: metadata?.max_value ?? null,
  };
};

/**
 * Constructs a unique key for identifying a scanned parameter.
 *
 * For experiment parameters, this returns the parameter ID as-is.
 * For device parameters (i.e., when namespace is "Devices"), it returns
 * the full access path used to uniquely identify the parameter, including
 * the device name.
 *
 * Example:
 *   makeScannedParamKey("laser_power", "Devices", "Laser A")
 *   → 'devices.device_proxies["Laser A"].laser_power'
 *
 * @param id - The parameter ID.
 * @param namespace - The parameter's namespace (e.g., "Devices" or an experiment namespace).
 * @param deviceNameOrDisplayGroup - Device name (for device parameters) or display group name.
 * @returns A string key uniquely identifying the scanned parameter.
 */
export const makeScannedParamKey = (
  id: string,
  namespace: string,
  deviceNameOrDisplayGroup: string,
): string =>
  namespace === "Devices"
    ? `devices.device_proxies["${deviceNameOrDisplayGroup}"].${id}`
    : id;

/**
 * Inverse of makeScannedParamKey: recovers the bare parameter id from a scanned
 * key. For device parameters it strips the `devices.device_proxies["<device>"].`
 * prefix; for other namespaces the key is already the bare id.
 *
 * @param scannedKey - The full scanned parameter key (as built by makeScannedParamKey).
 * @param namespace - The parameter's namespace (e.g., "Devices").
 * @param deviceNameOrDisplayGroup - Device name (for device parameters) or display group name.
 * @returns The bare parameter id.
 */
export const extractScannedParamId = (
  scannedKey: string,
  namespace: string,
  deviceNameOrDisplayGroup: string,
): string => {
  if (namespace !== "Devices") return scannedKey;
  const prefix = `devices.device_proxies["${deviceNameOrDisplayGroup}"].`;
  return scannedKey.startsWith(prefix) ? scannedKey.slice(prefix.length) : scannedKey;
};

/**
 * Returns the index of a scanned parameter within the scanned parameters list.
 *
 * This function checks if the given `paramId` exists in the `scannedParams` array
 * and returns its index if found. If the parameter is not found, it returns null.
 *
 * @param paramId - The full key identifying the parameter (as generated by makeScannedParamKey).
 * @param scannedParams - The list of scanned parameter keys.
 * @returns The index of the parameter in the scan list, or null if not found.
 */
export const getScanIndex = (
  paramId: string,
  scannedParams: string[],
): number | null => {
  const index = scannedParams.indexOf(paramId);
  return index !== -1 ? index : null;
};

/**
 * Determines if a parameter type can be scanned with numeric ranges.
 *
 * @param paramId - The parameter ID string containing type information.
 * @returns True if the parameter can be scanned (numeric types), false otherwise.
 */
export function isScannableParameterType(paramId: string): boolean {
  if (paramId.includes("param_type='ParameterTypes.BOOLEAN'")) {
    return false;
  }

  if (paramId.includes("param_type='ParameterTypes.ENUM'")) {
    return false;
  }

  return true;
}
