"""Adds repetitions column to job table

Revision ID: 4c4713742c14
Revises: 027f86f1812b
Create Date: 2024-08-14 11:10:22.504536

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c4713742c14"
down_revision: str | None = "027f86f1812b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_submissions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("repetitions", sa.Integer(), server_default="1", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_submissions", schema=None) as batch_op:
        batch_op.drop_column("repetitions")

    # ### end Alembic commands ###
