"""Adds parent_job_id to job table

Revision ID: e53ce613a1ed
Revises: 8640dcfde6f0
Create Date: 2024-08-09 08:27:52.849299

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e53ce613a1ed"
down_revision: str | None = "8640dcfde6f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_job_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("parent_job", "jobs", ["parent_job_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint("parent_job", type_="foreignkey")
        batch_op.drop_column("parent_job_id")
    # ### end Alembic commands ###
