"""Adds debug_mode column to job table

Revision ID: f5fd45fdded6
Revises: a8766054064d
Create Date: 2024-08-08 16:21:59.370658

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5fd45fdded6"
down_revision: str | None = "a8766054064d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("jobs") as batch_op:
        batch_op.add_column(
            sa.Column(
                "debug_mode", sa.Boolean(), server_default="False", nullable=False
            ),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs") as batch_op:
        batch_op.drop_column("debug_mode")
    # ### end Alembic commands ###
