"""add name column to scan_parameters

Revision ID: f60d837b7263
Revises: b18002636885
Create Date: 2026-03-17 10:37:26.977138

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f60d837b7263'
down_revision: str | None = 'b18002636885'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table('scan_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False, server_default=''))

    # Backfill: set name = variable_id for existing rows
    op.execute("UPDATE scan_parameters SET name = variable_id WHERE name = ''")

    with op.batch_alter_table('scan_parameters', schema=None) as batch_op:
        batch_op.alter_column('name', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_parameters', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
