"""Add realtime column to ScanParameter model

Revision ID: fc9af856df20
Revises: 2bc7556020cf
Create Date: 2025-09-18 13:13:16.093552

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc9af856df20"
down_revision: str | None = "2bc7556020cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_parameters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("realtime", sa.Boolean(), nullable=False, server_default="False")
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_parameters", schema=None) as batch_op:
        batch_op.drop_column("realtime")

    # ### end Alembic commands ###
