name: Create release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$tag" \
            --draft \
            --generate-notes
  build-binary:
    name: Build (Linux)
    runs-on: ubuntu-latest
    env:
      BIN_NAME: icon

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          curl -fsSL https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.GITLAB_TIQI_RPC_SSH_KEY }}

      - name: Add gitlab.phys.ethz.ch to known hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan gitlab.phys.ethz.ch >> ~/.ssh/known_hosts

      - name: Sync build dependencies
        env:
          GL_DEPLOY_USER: ${{ secrets.GITLAB_DEPLOY_USER }}
          GL_DEPLOY_TOKEN: ${{ secrets.GITLAB_DEPLOY_TOKEN }}
        run: |
          uv sync --no-dev --extra server --group build
          uv pip install "git+https://$GL_DEPLOY_USER:$GL_DEPLOY_TOKEN@gitlab.phys.ethz.ch/tiqi-projects/drivers/tiqi-zedboard.git"

      - name: Build with PyInstaller
        run: uv run pyinstaller icon.spec

      - name: Package artifact
        shell: bash
        run: |
          mkdir -p out
          cp "dist/${BIN_NAME}" "out/${BIN_NAME}-linux-amd64"

      - name: Upload binaries to GitHub Release
        env:
          tag: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$tag" out/** \
            --repo="$GITHUB_REPOSITORY"
